# Generated by Django 3.2 on 2021-04-26 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestionalternative')),
            ],
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='resposta',
            field=models.ManyToManyField(to='survey.SurveyQuestionAlternative'),
        ),
        migrations.AddField(
            model_name='survey',
            name='questoes',
            field=models.ManyToManyField(to='survey.SurveyQuestion'),
        ),
    ]
